# Build
custom_build(
    # name of the container image
    ref = 'mall-config',
    # Build the container image
    command = '../gradlew :mall-config:bootBuildImage --imageName $EXPECTED_REF',
    # Files to watch that trigger a new build
    deps = ['build.gradle', 'src']
)

# Deploy
k8s_yaml(kustomize('k8s'))

# Manage
k8s_resource('config-service', port_forwards=['8888'])