version: "3.8"
services:

  # Application

  catalog-service:
    depends_on:
      - mall-postgres
    image: "mall-catalog"
    container_name: "catalog-service"
    ports:
      - "9001:9001"
      - "8001:8001"
    environment:
      # Buildpacks environment variable to configure the numbers of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 8001
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mall-postgres:5432/mall_catalog
      - MALL_TESTDATA_ENABLED=true

  order-service:
    depends_on:
      - mall-postgres
    image: "mall-order"
    container_name: "order-service"
    ports:
      - "9002:9002"
      - "8002:8002"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - MALL_CATALOG_SERVICE_URL=http://catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://mall-postgres:5432/mall_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://mall-postgres:5432/mall_order

  edge-service:
    depends_on:
      - mall-redis
    image: "mall-edge"
    container_name: "edge-service"
    ports:
      - "9000:9000"
      - "8000:8000"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATA_REDIS_HOST=mall-redis
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002

  config-service:
    image: "mall-config"
    container_name: "config-service"
    ports:
      - "8888:8888"
      - "9888:9888"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888

  # Backing Services

  mall-postgres:
    image: "postgres:latest"
    container_name: "mall-postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mall
      - POSTGRES_PASSWORD=p@ssword
      # - POSTGRES_DB=mall_catalog
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  mall-redis:
    image: "redis:latest"
    container_name: "mall-redis"
    ports:
      - "6379:6379"