# Build
custom_build(
    # name of the container image
    ref = 'mall-dispatcher',
    # build the container image
    command = '../gradlew :mall-dispatcher:bootBuildImage --imageName $EXPECTED_REF',
    # files to watch that trigger a new build
    deps = ['build.gradle', 'src']
)

# Deploy
k8s_yaml(kustomize('k8s'))

# Manage
k8s_resource('dispatcher-service', port_forwards=['9003'])