apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/arch/cloud-native-mall/mall-catalog/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: catalog-config

images:
  - name: mall-catalog
    # will pull from remote registry
    #newName: ghcr.io/rigofunc/mall-catalog
    #newTag: latest

replicas:
  - name: catalog-service
    count: 2