apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/arch/cloud-native-mall/mall-catalog/k8s?ref=main

patches:
  - path: patch-env.yml
  - path: patch-volumes.yml
  - path: patch-resources.yml

configMapGenerator:
  - name: catalog-config
    behavior: merge
    files:
      - application-prod.yml

images:
  - name: mall-catalog
    newName: ghcr.io/arch/mall-catalog
    newTag: latest

replicas:
  - name: catalog-service
    count: 2