server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful

mall:
  greeting: Welcome to the local mall catalog!

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    username: mall
    password: p@ssword
    url: jdbc:postgresql://localhost:5432/mall_catalog
    hikari:
      connection-timeout: 2000  # 2s
      maximum-pool-size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/mall
  config:
    import: ""  # optional:configserver:
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000    # 5s
      fail-fast: false              # In production, set to true
      retry:
        initial-interval: 1000      # 1s
        max-attempts: 6
        max-interval: 2000          # 2s
        multiplier: 1.1

info:
  system: Cloud Native Mall

management:
  endpoints:
    web:
      exposure:
        include: info,refresh,flyway,health,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      mode: full

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"