apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9002"
    spec:
      containers:
        - name: order-service
          image: mall-order
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9002
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          env:
            - name: MALL_CATALOG_SERVICE_URI
              value: "http://catalog-service"
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service"
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://mall-postgres/mall_order"
            - name: SPRING_FLYWAY_URL
              value: "jdbc:postgresql://mall-postgres/mall_order"
            - name: SPRING_RABBITMQ_HOST
              value: mall-rabbitmq
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://mall-keycloak/realms/mall
          livenessProbe:
            httpGet:
              port: 9002
              path: /actuator/health/liveness
            initialDelaySeconds: 25
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 9002
              path: /actuator/health/readiness
            initialDelaySeconds: 25
            periodSeconds: 15