# Build
custom_build(
    # name of the container image
    ref = 'mall-order',
    # build the container image
    command = '../gradlew :mall-order:bootBuildImage --imageName $EXPECTED_REF',
    # files to watch that trigger a new build
    deps = ['build.gradle', 'src']
)

# Deploy
k8s_yaml(['k8s/deployment.yml', 'k8s/service.yml'])

# Manage
k8s_resource('order-service', port_forwards=['9002'])