server:
  shutdown: graceful
  port: 9002
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: order-service
  r2dbc:
    username: mall
    password: p@ssword
    url: r2dbc:postgresql://localhost:5432/mall_order
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  config:
    import: "optional:configserver:"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/mall
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000    # 5s
      fail-fast: false              # In production, set to true
      retry:
        initial-interval: 1000      # 1s
        max-attempts: 6
        max-interval: 2000          # 2s
        multiplier: 1.1
    function:
      definition: dispatchOrder
    stream:
      bindings:
        dispatchOrder-in-0:
          destination: order-dispatched
          group: ${spring.application.name}
        acceptedOrder-out-0:
          destination: order-accepted
      rabbit:
        bindings:
          acceptedOrder-out-0:
            producer:
              transacted: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
  rabbitmq:
    host: localhost
    port: 5672
    username: mall
    password: p@ssword
    connection-timeout: 5s
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/mall_order
mall:
  catalog-service-uri: "http://localhost:9001"